spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/concesionario
        username: root
        password:
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        show-sql: true
        propieties:
            hibernate:
                format-sql: true